apiVersion: v1
kind: Service
metadata:
  name: stockalert
  namespace: stockalert
  labels:
    app: stockalert
spec:
  type: NodePort
  selector:
    app: stockalert
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
